keycloak:
   auth-server-url: http://webs:8180/auth/
   realm: stiwa
   ssl-required: external
   principal-attribute: preferred_username
   use-resource-role-mappings: true
   resource: ${auth.client-id}
   credentials:
      secret: ${auth.client-secret}
   #bearer-only: true
   #public-client: false
   #cors: true 

spring:
   jackson:
      mapper:
         default_view_inclusion: true
      serialization:
         WRITE_NULL_MAP_VALUES: false
